### PR TITLE
Plug in own promise library for Mongoose

### LINKED ISSUE #29: Mongoose requires an alternative to their own mpromise library
Warning when running `node server.js`:
```
(node:178) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```
[StackOverflow](https://stackoverflow.com/questions/38138445/node3341-deprecationwarning-mongoose-mpromise) suggests using bluebird.

Will see if I can create a pull request today.

### PR DESCRIPTION
**Pull request by BenGitter**
fixes #29

### CODE REVIEW

**Comment by JacksonBates** [comment]
Hmm...separate issue, but Travis doesn't like contributions from forks. It removes the .env needed for oauth, and then can't run tests...I'll look into fixing that, or working around it.

See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by JacksonBates** [comment]
I can't believe what a simple fix that was - I've been tinkering with all sorts of nonsense in the travis.yml for the last hour!

**Comment by JacksonBates** [comment]
Ahem...@bengitter
image

**Comment by BenGitter** [comment]
No pressure, huh.

**Comment by JacksonBates** [comment]
There's plenty of low hanging fruit :)

I wasn't gonna bother trying for the shirt - then I made 3 PRs to Pairboard yesterday just with little housekeeping things and I noticed they counted!

**Comment by BenGitter** [comment]
afbeelding

**Pull request merged**
